#!/bin/sh
bspc monitor -d Λ Σ Δ Ω

# Set the border colors.
bspc config focused_border_color  "#f5e3a6"
bspc config normal_border_color   "#f2e5bc"
bspc config presel_feedback_color "#f5e3a6"



bspc config border_width        15
bspc config window_gap          10
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a emacs desktop='^2'state=tiled
bspc rule -a firefox desktop='^3'
bspc rule -a Sxiv state=floating

sxhkd &
polybar -c ~/.config/polybar/config bar &
sh .fehbg
